[project]
name = "monitor"
version = "0.1.0"
description = "TradingView Alert to DingTalk FastAPI Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0",
    "requests>=2.31.0",
    "pydantic>=2.5.0"
]
